export const home_SET_TOP_TEN_ON_SALE_BOOKS = "home_SET_TOP_TEN_ON_SALE_BOOKS";
export const home_SET_RECOMMENDED_BOOKS = "home_SET_RECOMMENDED_BOOKS";
export const home_SET_POPULAR_BOOKS = "home_SET_POPULAR_BOOKS";
export const home_SET_TAG_FEATURED_BOOKS = "home_SET_TAG_FEATURED_BOOKS";
